#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ActionSheetCSharp.Resource.Attribute.actionSheetBackground = global::Sample.Resource.Attribute.actionSheetBackground;
			global::ActionSheetCSharp.Resource.Attribute.actionSheetPadding = global::Sample.Resource.Attribute.actionSheetPadding;
			global::ActionSheetCSharp.Resource.Attribute.actionSheetStyle = global::Sample.Resource.Attribute.actionSheetStyle;
			global::ActionSheetCSharp.Resource.Attribute.actionSheetTextSize = global::Sample.Resource.Attribute.actionSheetTextSize;
			global::ActionSheetCSharp.Resource.Attribute.cancelButtonBackground = global::Sample.Resource.Attribute.cancelButtonBackground;
			global::ActionSheetCSharp.Resource.Attribute.cancelButtonMarginTop = global::Sample.Resource.Attribute.cancelButtonMarginTop;
			global::ActionSheetCSharp.Resource.Attribute.cancelButtonTextColor = global::Sample.Resource.Attribute.cancelButtonTextColor;
			global::ActionSheetCSharp.Resource.Attribute.otherButtonBottomBackground = global::Sample.Resource.Attribute.otherButtonBottomBackground;
			global::ActionSheetCSharp.Resource.Attribute.otherButtonMiddleBackground = global::Sample.Resource.Attribute.otherButtonMiddleBackground;
			global::ActionSheetCSharp.Resource.Attribute.otherButtonSingleBackground = global::Sample.Resource.Attribute.otherButtonSingleBackground;
			global::ActionSheetCSharp.Resource.Attribute.otherButtonSpacing = global::Sample.Resource.Attribute.otherButtonSpacing;
			global::ActionSheetCSharp.Resource.Attribute.otherButtonTextColor = global::Sample.Resource.Attribute.otherButtonTextColor;
			global::ActionSheetCSharp.Resource.Attribute.otherButtonTopBackground = global::Sample.Resource.Attribute.otherButtonTopBackground;
			global::ActionSheetCSharp.Resource.String.ApplicationName = global::Sample.Resource.String.ApplicationName;
			global::ActionSheetCSharp.Resource.String.Hello = global::Sample.Resource.String.Hello;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet = global::Sample.Resource.Styleable.ActionSheet;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_actionSheetBackground = global::Sample.Resource.Styleable.ActionSheet_actionSheetBackground;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_actionSheetPadding = global::Sample.Resource.Styleable.ActionSheet_actionSheetPadding;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_actionSheetTextSize = global::Sample.Resource.Styleable.ActionSheet_actionSheetTextSize;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_cancelButtonBackground = global::Sample.Resource.Styleable.ActionSheet_cancelButtonBackground;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_cancelButtonMarginTop = global::Sample.Resource.Styleable.ActionSheet_cancelButtonMarginTop;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_cancelButtonTextColor = global::Sample.Resource.Styleable.ActionSheet_cancelButtonTextColor;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_otherButtonBottomBackground = global::Sample.Resource.Styleable.ActionSheet_otherButtonBottomBackground;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_otherButtonMiddleBackground = global::Sample.Resource.Styleable.ActionSheet_otherButtonMiddleBackground;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_otherButtonSingleBackground = global::Sample.Resource.Styleable.ActionSheet_otherButtonSingleBackground;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_otherButtonSpacing = global::Sample.Resource.Styleable.ActionSheet_otherButtonSpacing;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_otherButtonTextColor = global::Sample.Resource.Styleable.ActionSheet_otherButtonTextColor;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheet_otherButtonTopBackground = global::Sample.Resource.Styleable.ActionSheet_otherButtonTopBackground;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheets = global::Sample.Resource.Styleable.ActionSheets;
			global::ActionSheetCSharp.Resource.Styleable.ActionSheets_actionSheetStyle = global::Sample.Resource.Styleable.ActionSheets_actionSheetStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int actionSheetBackground = 2130771969;
			
			// aapt resource value: 0x7f010009
			public const int actionSheetPadding = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int actionSheetStyle = 2130771968;
			
			// aapt resource value: 0x7f01000c
			public const int actionSheetTextSize = 2130771980;
			
			// aapt resource value: 0x7f010002
			public const int cancelButtonBackground = 2130771970;
			
			// aapt resource value: 0x7f01000b
			public const int cancelButtonMarginTop = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int cancelButtonTextColor = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int otherButtonBottomBackground = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int otherButtonMiddleBackground = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int otherButtonSingleBackground = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int otherButtonSpacing = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int otherButtonTextColor = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int otherButtonTopBackground = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int MyButton = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int button2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int button3 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button4 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionSheet = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public const int ActionSheet_actionSheetBackground = 0;
			
			// aapt resource value: 8
			public const int ActionSheet_actionSheetPadding = 8;
			
			// aapt resource value: 11
			public const int ActionSheet_actionSheetTextSize = 11;
			
			// aapt resource value: 1
			public const int ActionSheet_cancelButtonBackground = 1;
			
			// aapt resource value: 10
			public const int ActionSheet_cancelButtonMarginTop = 10;
			
			// aapt resource value: 6
			public const int ActionSheet_cancelButtonTextColor = 6;
			
			// aapt resource value: 4
			public const int ActionSheet_otherButtonBottomBackground = 4;
			
			// aapt resource value: 3
			public const int ActionSheet_otherButtonMiddleBackground = 3;
			
			// aapt resource value: 5
			public const int ActionSheet_otherButtonSingleBackground = 5;
			
			// aapt resource value: 9
			public const int ActionSheet_otherButtonSpacing = 9;
			
			// aapt resource value: 7
			public const int ActionSheet_otherButtonTextColor = 7;
			
			// aapt resource value: 2
			public const int ActionSheet_otherButtonTopBackground = 2;
			
			public static int[] ActionSheets = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int ActionSheets_actionSheetStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
