#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ActionSheetCSharp.Resource", IsApplication=false)]

namespace ActionSheetCSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int actionSheetBackground = 2130771969;
			
			// aapt resource value: 0x7f010009
			public static int actionSheetPadding = 2130771977;
			
			// aapt resource value: 0x7f010000
			public static int actionSheetStyle = 2130771968;
			
			// aapt resource value: 0x7f01000c
			public static int actionSheetTextSize = 2130771980;
			
			// aapt resource value: 0x7f010002
			public static int cancelButtonBackground = 2130771970;
			
			// aapt resource value: 0x7f01000b
			public static int cancelButtonMarginTop = 2130771979;
			
			// aapt resource value: 0x7f010007
			public static int cancelButtonTextColor = 2130771975;
			
			// aapt resource value: 0x7f010005
			public static int otherButtonBottomBackground = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int otherButtonMiddleBackground = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int otherButtonSingleBackground = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public static int otherButtonSpacing = 2130771978;
			
			// aapt resource value: 0x7f010008
			public static int otherButtonTextColor = 2130771976;
			
			// aapt resource value: 0x7f010003
			public static int otherButtonTopBackground = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public static int ApplicationName = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int Hello = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionSheet = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public static int ActionSheet_actionSheetBackground = 0;
			
			// aapt resource value: 8
			public static int ActionSheet_actionSheetPadding = 8;
			
			// aapt resource value: 11
			public static int ActionSheet_actionSheetTextSize = 11;
			
			// aapt resource value: 1
			public static int ActionSheet_cancelButtonBackground = 1;
			
			// aapt resource value: 10
			public static int ActionSheet_cancelButtonMarginTop = 10;
			
			// aapt resource value: 6
			public static int ActionSheet_cancelButtonTextColor = 6;
			
			// aapt resource value: 4
			public static int ActionSheet_otherButtonBottomBackground = 4;
			
			// aapt resource value: 3
			public static int ActionSheet_otherButtonMiddleBackground = 3;
			
			// aapt resource value: 5
			public static int ActionSheet_otherButtonSingleBackground = 5;
			
			// aapt resource value: 9
			public static int ActionSheet_otherButtonSpacing = 9;
			
			// aapt resource value: 7
			public static int ActionSheet_otherButtonTextColor = 7;
			
			// aapt resource value: 2
			public static int ActionSheet_otherButtonTopBackground = 2;
			
			public static int[] ActionSheets = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public static int ActionSheets_actionSheetStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
